SET SERVEROUTPUT ON;
-- CRIANDO PACKAGES NO PL/SQL
CREATE OR REPLACE PACKAGE PKG_HANGOUT_01 IS
  -- AUTHOR: EDVALDO SZYMONEK
  -- CREATED: 16/12/2014
  
  -- DENTRO DA PACKAGE NÃO PRECISA COLOCAR "CREATE OR REPLACE"
  PROCEDURE PR_NOVA_DATA_CONT(P_CODIGO IN NUMBER, P_CONTRATACAO IN DATE);
  
  FUNCTION FN_NOME_FUNCIONARIO(P_FUNCIONARIO IN NUMBER)
    RETURN VARCHAR2;
  
END PKG_HANGOUT_01;

-- CRIANDO CORPO DA PACKAGE
CREATE OR REPLACE PACKAGE BODY PKG_HANGOUT_01 IS
  
  PROCEDURE PR_NOVA_DATA_CONT(P_CODIGO IN NUMBER, P_CONTRATACAO IN DATE) IS
  BEGIN
    UPDATE EMP
      SET EMP.HIREDATE = P_CONTRATACAO
      WHERE EMP.EMPNO = P_CODIGO;
      
    DBMS_OUTPUT.PUT_LINE('FUNCIONÁRIO ATUALIZADO COM SUCESSO');
  END PR_NOVA_DATA_CONT;
  
  FUNCTION FN_NOME_FUNCIONARIO(P_FUNCIONARIO IN NUMBER) RETURN VARCHAR2 IS
  CURSOR
    CR_FUNCIONARIO (P_FUNCIONARIO IN NUMBER) IS
      SELECT EMP.ENAME
        FROM EMP
        WHERE EMP.EMPNO = P_FUNCIONARIO;
    
    V_NOME EMP.ENAME%TYPE;
    
  BEGIN
    OPEN CR_FUNCIONARIO(P_FUNCIONARIO);
      FETCH CR_FUNCIONARIO INTO V_NOME;
    CLOSE CR_FUNCIONARIO;
    
    RETURN V_NOME;
  END FN_NOME_FUNCIONARIO;
  
END PKG_HANGOUT_01;



-- CHAMA A PROCEDURE PR_NOVA_DATA_CONT;
BEGIN
  PKG_HANGOUT_01.PR_NOVA_DATA_CONT(7369, '16/12/2014');
  DBMS_OUTPUT.PUT_LINE(PKG_HANGOUT_01.FN_NOME_FUNCIONARIO(7369));
END;